# Generated by Django 5.0.1 on 2024-05-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('idCasa', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=50)),
                ('cantidad_personas', models.IntegerField()),
                ('Comuna', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'olivera_casa',
            },
        ),
    ]
