# Generated by Django 5.0.4 on 2024-06-14 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_moto_delete_casa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'olivera_cliente',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'olivera_marca',
            },
        ),
        migrations.CreateModel(
            name='TipoMoto',
            fields=[
                ('idTipoMoto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'olivera_tipomoto',
            },
        ),
        migrations.AlterField(
            model_name='moto',
            name='cilindrada',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='moto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.marca'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='ventas.cliente')),
            ],
            options={
                'db_table': 'olivera_pedido',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('idDetallePedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.moto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.pedido')),
            ],
            options={
                'db_table': 'olivera_detallepedido',
            },
        ),
        migrations.AlterField(
            model_name='moto',
            name='tipo_moto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.tipomoto'),
        ),
    ]
