# Generated by Django 5.0.4 on 2024-06-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_cliente_table_alter_detallepedido_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='idMarca',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tipomoto',
            name='idTipoMoto',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='tipomoto',
            name='nombre',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
